trigger:
  paths:
    exclude:
      - README.md
      - README_EN.md
      - LICENSE
      - .gitignore
      - deployments/*
  branches:
    exclude:
      - dev

resources:
  - repo: self
pool: "Azure Pipelines"
variables:
  image-repo: "bupt2018/memes-mcp"

stages:
  - stage: BuildAndPush
    displayName: BuildAndPush
    jobs:
      - job: BuildAndPush
        displayName: BuildAndPush

        steps:
          - task: CmdLine@2
            inputs:
              script: ' x=`echo "$(Build.SourceVersion)" | head -c 8`; echo "##vso[task.setvariable variable=SHORT_COMMIT]$x"'

          - task: Docker@2
            inputs:
              containerRegistry: "ACR"
              repository: "$(image-repo)"
              command: "buildAndPush"
              tags: "latest"
              Dockerfile: "**/Dockerfile"